spring.application.name=aml-diploma-project
server.port=${PORT:7777}
############# DATABASE CONNECTION ########################################
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aml}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1111}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
jwt.token.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
# Screening threshold (0.0 - 1.0)
screening.threshold=${SCREENING_THRESHOLD:0.80}